### PR TITLE
current year for copyright notice in example

### PR DESCRIPTION
**Pull request by PanderMusubi**
Perhaps support this via a `{{}}` macro.

### CODE REVIEW

**Comment by PanderMusubi** [comment]
One step further would be to add a start year in the python file and render for e.g. a value of 2018:
* in the year 2018: `2018`
* in the year 2019: `2018 – 2019`
* in the year 2020: `2018 – 2020`
* etc.

**Comment by greyli** [comment]
Please check the "Allow edits by maintainers" option so I can edit the file.

**Comment by PanderMusubi** [comment]
Do you have an url where I can find that setting?

**Comment by greyli** [comment]
It should be at the bottom right corner on this page.

image

**Comment by PanderMusubi** [comment]
Under `3 participants` I see only the avatars and then nothing. Perhaps it is because I have a free account? I can convert the PR into a draft. Is that recommendable?

**Comment by greyli** [comment]
Maybe it's because you are using the master branch. Please just add a `2018 –` before the current year, thank you.

**Comment by PanderMusubi** [comment]
Followed this convention https://en.wikipedia.org/wiki/Dash#Ranges_of_values

**Comment by greyli** [comment]
Merged, thanks!

**Pull request merged**
