### PR TITLE
Fix KeyError Exception if ENV isn't defined.

### PR DESCRIPTION
**Pull request by nuno-andre**
Also, the ternary conditional isn't needed. The comparison already returns a bool.

### CODE REVIEW

**Comment by greyli** [comment]
Thanks!

**Comment by greyli** [comment]
Do you actually get the `KeyError`? It seems that the `ENV` configuration variable was [defined by Flask](https://github.com/pallets/flask/blob/master/flask/app.py#L282) when the `app` instance was created.

**Comment by nuno-andre** [comment]
Thanks to you! Yes. I got it the exception with Flask 0.12.4, the last pre-1.0 (April 2018).

`FLASK_DEV` was introduced as of version 1.0. From 0.11 to 0.12 [the recommended method of enabling the development server](http://flask.pocoo.org/docs/0.12/server/) was through `FLASK DEBUG`. So before 1.0 _development server_ and _debug mode_ meant the same to Flask.

I made a PR to honor this equivalence that sets `dev = FLASK_DEBUG` only if there is not a FLASK_DEV.

**Comment by greyli** [comment]
Oh, you are right. I forgot the old version.

**Pull request merged**
