### PR TITLE
possible to translate actions header

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Comment by PanderMusubi** [comment]
Related question: similar translation could be implemented for `Previous` and `Next` in https://github.com/greyli/bootstrap-flask/blob/master/flask_bootstrap/templates/bootstrap/pagination.html#L6 but requires more complex implementation. Please advice on best course to take.

**Comment by PanderMusubi** [comment]
This functionality can besides tranlations also be used to show `Action` for `Actions` when only one type of action is displayed or to use `Prev` as abbreviation for `Previous`.

**Comment by greyli** [comment]
Good change! I just changed the parameter name to `actions_title` to improve consistency. However, I don't think it's a good idea to increase the complexity of `render_pager` since we already can use the existing parameters to customize the text.

**Comment by PanderMusubi** [comment]
Thanks for merging. Complexity of `render_pager` should indeed not increase, but perhaps there is a way to override Previous and Next in a less complex way.

**Comment by PanderMusubi** [comment]
Follow up question, the values of alt for `View`, `Edit` and `Delete` in `render_table` should also be configurable. Okay that I propose a fix in another PR?

**Comment by greyli** [comment]
> Okay that I propose a fix in another PR?

Sure, please be sure to reflect this change in the documentation (also update for `actions_title`).

**Comment by PanderMusubi** [comment]
Please see https://github.com/greyli/bootstrap-flask/pull/98

**Pull request merged**
