### PR TITLE
switch field implrementation bootstrap5

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Comment by greyli** [comment]
Please rebase to remove the unrelated commit from the base branch.

**Comment by PanderMusubi** [comment]
No idea why that other commit was included. Is this okay now?

**Comment by greyli** [comment]
Looks good now.

I think it's because you used the same branch. Checking out a new branch may solve the issue.

**Comment by PanderMusubi** [comment]
Ah, yes, I understand, my fork needs to branch your branch.

**Pull request merged**
