### PR TITLE
Add a render_flashed_messages macro

### PR DESCRIPTION
**Pull request by neil-s**
Following up on #4 ,  and based on bootstrap-flask's implementation, with a name updated to match this project's naming style.

If you are open to this, I'll submit another commit to update the documentation and mention this macro. 

I haven't fully tested this with Bootstrap 4.

### CODE REVIEW

**Comment by neil-s** [comment]
OK this obviously doesn't work yet. Please ignore this PR, I'll update with commits that make it actually work.

**Comment by greyli** [comment]
Some advice:

* Rewrite it to make it work with Bootstrap 4.
* Let user to pass category name, note that there are 8 category types in Bootstrap 4.
* Match default category (`message`) to primary alert (`class="alert alert-primary"`).

**Comment by SobieskiCodes** [comment]
Take it this is no longer on the board? Really the only thing missing.

**Comment by greyli** [comment]
@SobieskiCodes I'll implement this based on this PR. Please [vote](https://github.com/greyli/bootstrap-flask/issues/38) for the macro name!

**Comment by greyli** [comment]
Thanks for working on this! This pr was replaced with #39.

**Pull request closed without merging**
