### PR TITLE
remove unwanted hover underline next to view and edit icons

### PR DESCRIPTION
**Pull request by PanderMusubi**
This remove small blue line thta shows up next to the view and edit icons when hovering mouse over them.

Question, the delete icon doens't look as it is vertivally aligned with the other two icons. Probably because it is inside a form. Any suggestions on how to fix that?

### CODE REVIEW

**Comment by PanderMusubi** [comment]
Second question, what is the upstream source of these three icons?

**Comment by greyli** [comment]
> Question, the delete icon doens't look as it is vertivally aligned with the other two icons. Probably because it is inside a form. Any suggestions on how to fix that?

The form generates a little space under the image, I didn't find a proper way to remove it yet.

> what is the upstream source of these three icons?

https://icons.getbootstrap.com/

**Comment by PanderMusubi** [comment]
Thanks. Can these icons be supported via a CDN in the example? And serve as documentation how users can do that themselves. Continue this in https://github.com/greyli/bootstrap-flask/issues/48 ?

Shall I make a new issue for the icon spacing?

**Comment by greyli** [comment]
> Can these icons be supported via a CDN in the example?

I didn't find a CDN provider support Bootstrap Icons. (I'm working on #48)

> Shall I make a new issue for the icon spacing?

Sure.

**Pull request merged**
