### PR TITLE
render switch for boolean

### PR DESCRIPTION
**Pull request by PanderMusubi**
Works for Bootstrap 4, not yet for Bootstrap 5. need help for that part.

The following one liner is probably the fix for version 5, but there is no forms.html for version 5 to add that.

    <div class="form-group form-check{% if form_type == "inline" %} form-check-inline{% endif %}{% if field.type == 'SwitchField' %} form-switch{% endif %}">

### CODE REVIEW

**Comment by greyli** [comment]
I think it's reasonable to make `SwitchField` a built-in class, what do you think?

**Comment by PanderMusubi** [comment]
> I think it's reasonable to make `SwitchField` a built-in class, what do you think?

I agree. In which file should it be added then?

**Comment by greyli** [comment]
> In which file should it be added then?

Just put it to the `__init__.py` file.

**Comment by PanderMusubi** [comment]
Done.

For the Bootstrap 5 implementation, waiting for `flask_bootstrap/templates/bootstrap5/form.html` to be created.

**Comment by PanderMusubi** [comment]
@greyli If you want and all is okay, this can be merged. I can make a new branch and PR when Bootstrap5 form.html becomes available.

**Comment by greyli** [comment]
Looks good. Please add some tests for this feature, then add an entry to the changelog.

**Comment by PanderMusubi** [comment]
> Looks good. Please add some tests for this feature, then add an entry to the changelog.

Added.

**Comment by greyli** [comment]
Merged, thanks!

**Pull request merged**
